### ISSUE TITLE
stretchr/testify/suite panic: reflect: Call with too few input arguments

### ISSUE THREAD

**Issue by at15** [xephonhq/xephon-b#11]
````
ok  	github.com/xephonhq/xephon-b/pkg/generator	0.002s	coverage: 85.7% of statements
=== RUN   TestSerializerInterface
=== RUN   TestSerializeTestSuite
=== RUN   TestDebugSerializer
--- FAIL: TestDebugSerializer (0.00s)
panic: reflect: Call with too few input arguments [recovered]
	panic: reflect: Call with too few input arguments

goroutine 7 [running]:
panic(0x6a8ca0, 0xc4201f86d0)
	/home/at15/app/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4200943c0)
	/home/at15/app/go/src/testing/testing.go:579 +0x25d
panic(0x6a8ca0, 0xc4201f86d0)
	/home/at15/app/go/src/runtime/panic.go:458 +0x243
reflect.Value.call(0xc4201e0ba0, 0xc420036530, 0x13, 0x70fb7d, 0x4, 0xc420034760, 0x1, 0x1, 0x506788, 0x70b060, ...)
	/home/at15/app/go/src/reflect/value.go:358 +0x13c1
reflect.Value.Call(0xc4201e0ba0, 0xc420036530, 0x13, 0xc420059f40, 0x1, 0x1, 0x87c140, 0x0, 0xf6)
	/home/at15/app/go/src/reflect/value.go:302 +0xa4
github.com/xephonhq/xephon-b/vendor/github.com/stretchr/testify/suite.Run.func2(0xc4200943c0)
	/home/at15/workspace/src/github.com/xephonhq/xephon-b/vendor/github.com/stretchr/testify/suite/suite.go:95 +0x1cb
testing.tRunner(0xc4200943c0, 0xc420223960)
	/home/at15/app/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/home/at15/app/go/src/testing/testing.go:646 +0x2ec
FAIL	github.com/xephonhq/xephon-b/pkg/serialize	0.005s
````

On line 95 is `method.Func.Call([]reflect.Value{reflect.ValueOf(suite)})`, however after seeing https://github.com/pavlo/gosuite/blob/master/gosuite.go#L56, 
I changed it to `method.Func.Call([]reflect.Value{reflect.ValueOf(suite), reflect.ValueOf(t)})` and the test works 

Possible reasons 

-  [x] I am not using it properly, since [Ayi](https://github.com/dyweb/Ayi/blob/master/app/git/config_test.go) also work

**Comment by at15** [comment]
should use `suite.T()` to get test context instead of expect it from parameter. (Though I actually prefer the latter)

**Comment by jutkko** [comment]
Another potential cause for this is using a `func (s *TestMySuite) TestMyFunction(t *testing.T)` instead of `func (s *TestMySuite) TestMyFunction()`
